 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: choco install mingw innosetup
       - run: cd ISCompiler && g++ ISCompil.cpp -o ISCompil.exe
       - run: cd ISCompiler && ./ISCompil.exe
