trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: cmd /c install.bat
  displayName: 'Install'
  
- script: cmd /c install-cxp.bat
  displayName: "Install changing PowerShell's execution policy"
