trigger:
- master

jobs:
- job: Windows_old

  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      cd old
      install.bat
    displayName: 'Install'

  - script: |
      cd old
      install-cxp.bat
    displayName: 'Install changing the execution policy'