trigger:
- master

jobs:
- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: BatchScript@1
    inputs:
      filename: 'install.bat'
    displayName: 'Install'

  - task: BatchScript@1
    inputs:
      filename: 'install-cxp.bat'
    displayName: "Install changing PowerShell's execution policy"
