jobs:
- job: Windows_x64

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: BatchScript@1
    inputs:
      filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
      modifyEnvironment: true
    displayName: 'Enabling VS2019 Developer Command Prompt'

  - script: |
      cd ISCompiler
      cl.exe ISCompil.cpp
    displayName: 'Compiling ISCompil.cpp'

  - script: |
      cd ISCompiler
      ISCompil.exe
    displayName: 'Compiling correct version of OpenSSH for Windows - Installer using ISCompil.exe'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\x64\OpenSSHforWindows-Installer-x64.exe'
      artifact: 'OpenSSH for Windows - Installer x64 setup'
      publishLocation: 'pipeline'
    displayName: 'Publish Pipeline Artifacts'

- job: Windows_x86

  pool:
    vmImage: 'windows-latest'

  steps:
  - script: 'cmd /c "C:\Program Files (x86)\Inno Setup 6\iscc.exe" OpenSSH-Win32.iss'
    displayName: 'Compiling OpenSSH for Windows - Installer x86'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\x86\OpenSSHforWindows-Installer-x86.exe'
      artifact: 'OpenSSH for Windows - Installer x86 setup'
      publishLocation: 'pipeline'
    displayName: 'Publish Pipeline Artifacts'
