name: PowerShell Install (old)

on:
  push:
    branches: [ old ]
  pull_request:
    branches: [ old ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install
      run: cmd /c install.bat

    - name: Install changing execution policy
      run: cmd /c install-cxp.bat
