name: PowerShell Install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install
      run: powershell ./chocolateyinstall.ps1
      
    - name: Refresh environment variables
      run: refreshenv.cmd
